// Generated by CoffeeScript 1.3.3
var TokenBuilder, assert, path,
  _this = this;

path = require("path");

TokenBuilder = require(path.join(__dirname, "../lib/tokenBuilder"));

assert = require("assert");

require("should");

describe('TokenBuilder', function() {
  return describe('#new', function() {
    return it("should return a attributesString", function() {
      var obj, tokenBuilder;
      obj = {
        a: 1,
        b: 2,
        d: 1,
        c: 5
      };
      tokenBuilder = new TokenBuilder(obj);
      tokenBuilder.attributesString.should.equal('a=1&b=2&c=5&d=1');
      return tokenBuilder.token.should.equal('577e9c8046f4871de9df6069be1745f5');
    });
  });
});
