// Generated by CoffeeScript 1.3.3
var Application, assert, fs, path, yaml,
  _this = this;

path = require("path");

fs = require("fs");

Application = require(path.join(__dirname, "../lib/application"));

assert = require("assert");

yaml = require("js-yaml");

require("should");

describe('Application', function() {
  return describe('#constructor', function() {
    return it("should new a application", function() {
      var application, config;
      config = {
        port: 3000,
        sub_apps_dir: path.join(__dirname, 'sub_apps'),
        ssl: true,
        ssl_key: "server.key",
        ssl_cert: "server.crt",
        socket: {
          port: 8088,
          subscribe: {
            host: '192.168.2.18',
            port: 6379,
            channel: 'lottory1'
          }
        }
      };
      application = new Application(config);
      console.log(application.subApplicationDirs());
      return application.subApplicationDirs().indexOf(path.join(__dirname, 'sub_apps/example')).should.not.equal(-1);
    });
  });
});
