// Generated by CoffeeScript 1.4.0
var Response, assert, path, _,
  _this = this;

path = require("path");

_ = require("underscore");

Response = require(path.join(__dirname, "../lib/response"));

assert = require("assert");

require("should");

describe('Response', function() {
  return describe('#constructor()', function() {});
});
