// Generated by CoffeeScript 1.4.0
var SubApplication, assert, fs, path, yaml,
  _this = this;

path = require("path");

fs = require("fs");

SubApplication = require(path.join(__dirname, "../lib/sub_application"));

yaml = require("js-yaml");

assert = require("assert");

require("should");

describe("SubApplication", function() {
  return describe("#constructor", function() {
    return it("should create a SubApplication instance", function(done) {
      var subApplication;
      subApplication = new SubApplication(path.join(__dirname, "sub_apps/example"));
      assert.equal(typeof (subApplication.buildController()), "function");
      assert.equal(subApplication.config.redis.master.host, 'localhost');
      return subApplication.redis('master').set('test_key01', 'test_val01', function(err, res) {
        return subApplication.redis('master').get('test_key01', function(err, res) {
          res.should.equal('test_val01');
          return done();
        });
      });
    });
  });
});
