// Generated by CoffeeScript 1.4.0
var SubApplicationEnvironment, assert, fs, path, yaml,
  _this = this;

path = require("path");

fs = require("fs");

SubApplicationEnvironment = require(path.join(__dirname, "../lib/sub_application_environment"));

yaml = require("js-yaml");

assert = require("assert");

require("should");

describe('SubApplicationEnvironment', function() {
  return describe('#constructor', function() {
    return it("should create a new env", function(done) {
      var config;
      config = yaml.load(fs.readFileSync(path.join(__dirname, 'sub_apps/example/config.yml'), 'utf8'));
      console.log(subenv.redis());
      return subenv.redis().set('keytest', 'valtest', function(err, res) {
        return subenv.redis().get('keytest', function(err, res) {
          res.should.equal('valtest');
          return done();
        });
      });
    });
  });
});
