// Generated by CoffeeScript 1.3.3
var Params, _;

_ = require("underscore");

Params = (function() {

  function Params() {}

  Params.build = function(request) {
    var paramters;
    paramters = {};
    _.extend(paramters, request.params, request.body, request.query);
    return paramters;
  };

  return Params;

})();

module.exports = Params;
