// Generated by CoffeeScript 1.3.3
var SubApplication, fs, path, redis, yaml, _;

yaml = require('js-yaml');

fs = require('fs');

path = require('path');

redis = require('redis');

_ = require('underscore');

SubApplication = (function() {

  function SubApplication(dirname) {
    this.dirname = dirname;
    this.config = yaml.load(fs.readFileSync(path.join(this.dirname, 'config.yml'), 'utf8'));
    this.createRedisConns();
  }

  SubApplication.prototype.buildController = function() {
    return function() {};
  };

  SubApplication.prototype.redis = function(type) {
    if (type == null) {
      type = 'slave';
    }
    return this.redisConns[type];
  };

  SubApplication.prototype.createRedisConns = function() {
    var _this = this;
    this.redisConns = {};
    return _.each(this.config.redis, function(val, key) {
      return _this.redisConns[key] = redis.createClient(val);
    });
  };

  return SubApplication;

})();

module.exports = SubApplication;
