// Generated by CoffeeScript 1.4.0
var _this = this,
  __slice = [].slice;

module.exports = {
  setBeforeFilters: function() {
    var options;
    options = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  },
  actions: {},
  action: function() {
    return console.log("@@@@@@@@@@@@@@@@@");
  }
};
