// Generated by CoffeeScript 1.4.0
var SubApplicationEnviroment, redis, _;

_ = require('underscore');

redis = require('redis');

SubApplicationEnviroment = (function() {

  function SubApplicationEnviroment(config) {
    this.config = config;
    this.setRedises();
  }

  SubApplicationEnviroment.prototype.setRedises = function() {
    var _this = this;
    if (this.config.redis !== void 0) {
      this.redises = {};
      return _.each(this.config.redis, function(val, key) {
        return _this.redises[key] = redis.createClient(val);
      });
    }
  };

  SubApplicationEnviroment.prototype.setDatabases = function() {};

  SubApplicationEnviroment.prototype.setRouter = function() {
    return this.router = this.config.router;
  };

  SubApplicationEnviroment.prototype.redis = function(connection) {
    if (connection == null) {
      connection = 'slave';
    }
    return this.redises[connection];
  };

  return SubApplicationEnviroment;

})();

module.exports = SubApplicationEnviroment;
