// Generated by CoffeeScript 1.4.0
var TokenBuilder, crypto, _;

_ = require('underscore');

crypto = require('crypto');

TokenBuilder = (function() {

  function TokenBuilder(object) {
    var md5,
      _this = this;
    this.object = object;
    this.attributes = _.map(this.object, function(val, key) {
      return "" + key + "=" + val;
    });
    this.attributes = _.sortBy(this.attributes, function(pair) {
      return pair;
    });
    this.attributesString = this.attributes.join("&");
    md5 = crypto.createHash('md5');
    this.token = md5.update(this.attributesString, 'utf8').digest("hex");
  }

  return TokenBuilder;

})();

module.exports = TokenBuilder;
