master_server: 
  # host: ct.shoptrekkers.com
  host: 127.0.0.1
  port: 8444
slave_server: 
  # host: 192.168.2.18
  host: 127.0.0.1
  port: 8443
master_flags:
  act: 
    - set
  scr: 
    - login
    - login01
    - _login02
    - _login03
    - _reg02