// Generated by CoffeeScript 1.3.3
var fs, path, yaml;

path = require("path");

fs = require("fs");

yaml = require("js-yaml");

global.config = yaml.load(fs.readFileSync(path.join(__dirname, 'mi7.yml'), 'utf8'));

if (global.config.ssl) {
  global.config.ssl_config = {};
  global.config.ssl_config.key = fs.readFileSync(path.join(__dirname, global.config.ssl_key));
  global.config.ssl_config.cert = fs.readFileSync(path.join(__dirname, global.config.ssl_cert));
}
